# Generated by Django 2.1.7 on 2019-02-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrtnr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnplurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
