# Generated by Django 2.1.7 on 2019-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrtnr', '0002_auto_20190215_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnplurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
