# Generated by Django 2.1.7 on 2019-02-15 20:16

from django.db import migrations, models
import shrtnr.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shrtnr', '0003_pnplurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnplurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shrtnr.validators.url_validate]),
        ),
    ]
