# Generated by Django 2.1.7 on 2019-02-16 09:31

from django.db import migrations, models
import shrtnr.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shrtnr', '0004_auto_20190215_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnplurl',
            name='url',
            field=models.CharField(max_length=200, validators=[shrtnr.validators.url_validate]),
        ),
    ]
